[package]
name = "test_08_https_rest"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
openssl = { version = "0.10", features = ["vendored"] }
